import 'dart:io';
import 'package:yaml/yaml.dart';
import '../models/translation_config.dart';

/// Service for managing configuration files
class ConfigService {
  static const String configFileName = 'ai_translation_generator.yaml';

  /// Check if config file exists in current directory
  bool configExists() {
    return File(configFileName).existsSync();
  }

  /// Create default configuration file
  Future<void> createDefaultConfig() async {
    final config = TranslationConfig.defaultConfig();
    final yamlContent = _generateYamlContent(config);

    await File(configFileName).writeAsString(yamlContent);
  }

  /// Load configuration from file
  Future<TranslationConfig> loadConfig() async {
    if (!configExists()) {
      throw Exception(
        'Configuration file not found. Run "aitranslation init" first.',
      );
    }

    try {
      final file = File(configFileName);
      final content = await file.readAsString();
      final yaml = loadYaml(content);

      if (yaml is! Map) {
        throw Exception('Invalid YAML format');
      }

      return TranslationConfig.fromMap(Map<String, dynamic>.from(yaml));
    } catch (e) {
      if (e is YamlException) {
        throw Exception('Invalid YAML syntax: ${e.message}');
      } else {
        throw Exception('Failed to load configuration: ${e.toString()}');
      }
    }
  }

  /// Validate configuration format and content
  Future<bool> validateConfig() async {
    try {
      final config = await loadConfig();

      if (!config.isValid) {
        throw Exception(
          'Configuration is invalid: languages and strings must not be empty',
        );
      }

      // Validate language codes (basic check)
      for (final lang in config.languages) {
        if (lang.length < 2 || lang.length > 5) {
          throw Exception('Invalid language code: $lang');
        }
      }

      return true;
    } catch (e) {
      throw Exception('Configuration validation failed: ${e.toString()}');
    }
  }

  String _generateYamlContent(TranslationConfig config) {
    final buffer = StringBuffer();
    buffer.writeln('# AI Translation Generator Configuration');
    buffer.writeln('# Generated by aitranslation init');
    buffer.writeln();
    buffer.writeln('languages:');
    for (final lang in config.languages) {
      buffer.writeln('  - $lang');
    }
    buffer.writeln();
    buffer.writeln('strings:');
    for (final str in config.strings) {
      buffer.writeln('  - $str');
    }
    return buffer.toString();
  }

  /// Get the current working directory
  String getCurrentDirectory() {
    return Directory.current.path;
  }
}
